<?php

  $agentName = array (
    'aljohnson'     => 'Alex Johnson',
    'agonzales'     => 'Angela Gonzales',
    'ahendon'       => 'Anthony Hendon',
    'amacias'       => 'April Macias',
    'anewman'       => 'Angela Newman',
    'bdecker'       => 'Bryan Decker',
    'chkelley'      => 'Charles Kelly',
    'cdriskell'     => 'Chris Driskell',
    'chmoran'       => 'Christian Moran',
    'dameyer'       => 'David Meyer',
    'dneal'         => 'David Neal',
    'dsims'         => 'Don Sims',
    'gdeharo'       => 'Gennifer DeHaro',
    'gthompson'     => 'Greg Thompson',
    'ianderson'     => 'Ira Anderson',
    'jzamora'       => 'Jason Zamora',
    'jpinion'       => 'Janna Pinion',
    'jemcavin'      => 'Jessica McAvin',
    'jedupree'      => 'Jeffrey Dupree',
    'kkumi'         => 'Kwabena Kumi Aikins',
    'sroberts'      => 'Kay Roberts',
    'macampbell'    => 'Margaret Campbell',
    'mendrys'        => 'Mark Edrys',
    'mbarth'        => 'Matthew Barth',
    'mwildman'      => 'Mercedes Widman',
    'pgarza'        => 'Paulino Garza',
    'rhagemann'     => 'Richard Hagemann',
    'rmanley'       => 'Robert Manley',
    'rmcneil'       => 'Robert McNeil',
    'sseals'        => 'Suat Seals',
    'scooper'       => 'Stephen Cooper',
    'wcrosby'       => 'William Crosby'
    )
?>